### ISSUE TITLE
Enable third party restrictions to Polyhack organisation

### ISSUE THREAD

**Issue by sporto** [polyhack/polyhack.github.io#28]
@nicholasf 	

Since some github API changes earlier this week several CIs (Jenkins, Travis) are asking to re-authorize github account.

![authorize travis ci 2015-02-26 14-57-29](https://cloud.githubusercontent.com/assets/1005498/6386118/21f198f6-bdc8-11e4-842a-e64e7348d95c.png)

They are all asking for full access to private repos on all the organisations you are part of.

In order to disallow this the organisation needs to have third party restrictions set to on.

https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/

**Comment by nicholasf** [comment]
Thanks @sporto. Will look into this tomorrow or someone else in the owners group can tonight otherwise.

**Comment by SomeoneWeird** [comment]
Done.
